In [1]:
#numerical computing packages
from __future__ import absolute_import, division,print_function,unicode_literals
import numpy as np
import pandas as pd
import scipy
from scipy.stats import norm
from scipy import stats
from numpy.random import choice
np.random.seed(99)

#visualization packages
import plotly as pl
import plotly.offline as py
import plotly.graph_objs as go
from plotly.subplots import make_subplots
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')
from matplotlib import rcParams
from _plotly_future_ import v4_subplots
import missingno as msno

#ML packages
import sklearn
from sklearn.model_selection import train_test_split,cross_val_score
import sklearn.linear_model as linear_model
import xgboost as xgb
from sklearn.model_selection import KFold
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import category_encoders as ce
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression,LogisticRegression,RidgeCV, LassoCV, ElasticNetCV
from sklearn.feature_selection import SelectFromModel
import mglearn
from sklearn.metrics import accuracy_score
import category_encoders as ce
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, make_scorer

#statistical pakages
from scipy.stats import skew
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.multicomp import (pairwise_tukeyhsd,
                                         MultiComparison)
#jupyter notebook specfic packges
import warnings
warnings.filterwarnings('ignore')
py.init_notebook_mode(connected=True)
pd.options.display.max_columns = None
from IPython.display import HTML, display

#tensorflow packages
import tensorflow as tf
from tensorflow import keras

#user defined functions
from AllFunctions.runstoreproc import runstoreprocedure
from AllFunctions.runsql import runcommand
from AllFunctions.sqlcommandcreatedf import exportdata

In [2]:
#encoding the data using one of three methods 

'''
1. One hot encoding 
Since there are many columns with more number of dimensions, the problem might face curse of dimensionality

3. Hashing 
works well if there are many distinct categories. There might be collisions if there are some overlapping columns. But the 
curse of dimensionality is solved.Like OneHot but fewer dimensions, some info loss due to collisions. Nominal, ordinal.

4. Backward difference encoding
the mean of the dependent variable for a level is compared with the mean of the dependent variable for the prior level. 
'''

def onehotencoded(df):
    return pd.get_dummies(df)

def binaryencoded(df):
    #create a binary encoded object
    be=ce.BinaryEncoder(df.columns.values)
    #fit and transform the data
    return be.fit_transform(df)
    
def hashingencoded(df):
    #create a hashing encoder object
    he=ce.HashingEncoder(df.columns.values)
    #fit and transofrm on the data
    return he.fit_transform(df)

def backwarddifferenceencoded(df):
    #create a backward deference encoding
    bd=ce.BackwardDifferenceEncoder(df.columns.values)
    return bd.fit_transform(df)

In [3]:
serv ='NMALI-T450S'
DB ='Event'

In [ ]:
com ='Select top 100000 * from vw_event with (NOEXPAND)'
df=exportdata(com,DB,serv)

In [10]:
df

,int_id,int_type_id,int_type_name,repid,rep_act_type_id,rep_act_type_name,acct_id,facilityid,time_zone,duration,crea_from_sugg,start_date_time,start_date,date_Str,Wk_str,Year,Month,days,hours,minutes,seconds,meridiem,day,isweekday,isworkinghours,Quarter,Prod_id,Prod_Count,Pid1,Pid2,Pid3,Pid4,Pid5,Pid6,Pid7,Pid8,Pid9,Pid10,Pid11,Pid12,Pid13,Pid14,Pid15,Pid16,Pid17,Pid18,Pid19,isdeleted,iscompleted
0,220638585,11,SEND_ANY,2980,12,SEND_ANY,221720,None,America/Chicago,0,0,2017-12-31 15:45:11,2017-12-31,20171231,20180105,2017,12,31,03,45,11,PM,Sunday,0,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
1,220638604,11,SEND_ANY,2594,12,SEND_ANY,39973,None,America/Chicago,0,0,2017-12-04 16:20:00,2017-12-04,20171204,20171208,2017,12,04,04,20,00,PM,Monday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
2,220638605,11,SEND_ANY,2267,12,SEND_ANY,3715,None,America/Chicago,0,0,2017-12-26 22:30:00,2017-12-26,20171226,20171229,2017,12,26,10,30,00,PM,Tuesday,1,0,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
3,220638606,11,SEND_ANY,2594,12,SEND_ANY,23246132,None,America/Chicago,0,0,2017-12-04 16:40:00,2017-12-04,20171204,20171208,2017,12,04,04,40,00,PM,Monday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
4,220638607,11,SEND_ANY,2025,12,SEND_ANY,20797,None,America/Los_Angeles,0,0,2017-12-12 18:30:00,2017-12-12,20171212,20171215,2017,12,12,06,30,00,PM,Tuesday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
5,220638608,11,SEND_ANY,3378,12,SEND_ANY,377176,None,America/Chicago,0,0,2017-12-28 18:00:00,2017-12-28,20171228,20171229,2017,12,28,06,00,00,PM,Thursday,1,1,Q4\r,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1
6,220638609,11,SEND_ANY,2267,12,SEND_ANY,65776,None,America/Chicago,0,0,2017-12-22 22:00:00,2017-12-22,20171222,20171222,2017,12,22,10,00,00,PM,Friday,1,0,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
7,220638610,11,SEND_ANY,2594,12,SEND_ANY,39973,None,America/Chicago,0,0,2017-12-04 16:20:00,2017-12-04,20171204,20171208,2017,12,04,04,20,00,PM,Monday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
8,220638611,11,SEND_ANY,2594,12,SEND_ANY,23246132,None,America/Chicago,0,0,2017-12-04 16:40:00,2017-12-04,20171204,20171208,2017,12,04,04,40,00,PM,Monday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
9,220638612,11,SEND_ANY,2875,12,SEND_ANY,277717,None,America/Chicago,0,0,2017-12-31 20:25:33,2017-12-31,20171231,20180105,2017,12,31,08,25,33,PM,Sunday,0,0,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
10,220638613,11,SEND_ANY,2980,12,SEND_ANY,277617,None,America/Chicago,0,0,2017-12-20 15:33:08,2017-12-20,20171220,20171222,2017,12,20,03,33,08,PM,Wednesday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
11,220638614,11,SEND_ANY,2980,12,SEND_ANY,215135,None,America/Chicago,0,0,2017-12-20 18:01:39,2017-12-20,20171220,20171222,2017,12,20,06,01,39,PM,Wednesday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
12,220638615,11,SEND_ANY,2980,12,SEND_ANY,326531,None,America/Chicago,0,0,2017-12-21 18:53:47,2017-12-21,20171221,20171222,2017,12,21,06,53,47,PM,Thursday,1,1,Q4\r,1088,13,0,1,0,1,1,0,1,1,0,0,0,1,1,1,1,1,1,1,1,0,1
13,220638616,11,SEND_ANY,2980,12,SEND_ANY,277705,None,America/Chicago,0,0,2017-12-21 17:09:11,2017-12-21,20171221,20171222,2017,12,21,05,09,11,PM,Thursday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
14,220638617,11,SEND_ANY,2267,12,SEND_ANY,3715,None,America/Chicago,0,0,2017-12-26 22:30:00,2017-12-26,20171226,20171229,2017,12,26,10,30,00,PM,Tuesday,1,0,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
15,220638618,11,SEND_ANY,3140,12,SEND_ANY,223095,None,America/Chicago,0,0,2017-12-31 15:16:21,2017-12-31,20171231,20180105,2017,12,31,03,16,21,PM,Sunday,0,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
16,220638619,11,SEND_ANY,2267,12,SEND_ANY,3715,None,America/Chicago,0,0,2017-12-26 22:30:00,2017-12-26,20171226,20171229,2017,12,26,10,30,00,PM,Tuesday,1,0,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
17,220638620,11,SEND_ANY,2875,12,SEND_ANY,278155,None,America/Chicago,0,0,2017-12-31 20:26:02,2017-12-31,20171231,20180105,2017,12,31,08,26,02,PM,Sunday,0,0,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
18,220638621,11,SEND_ANY,2267,12,SEND_ANY,65776,None,America/Chicago,0,0,2017-12-22 22:00:00,2017-12-22,20171222,20171222,2017,12,22,10,00,00,PM,Friday,1,0,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
19,220638622,11,SEND_ANY,2369,12,SEND_ANY,182142,None,America/Chicago,0,0,2017-12-15 20:01:07,2017-12-15,20171215,20171215,2017,12,15,08,01,07,PM,Friday,1,0,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
20,220638623,11,SEND_ANY,3140,12,SEND_ANY,246612,None,America/Chicago,0,0,2017-12-31 15:16:53,2017-12-31,20171231,20180105,2017,12,31,03,16,53,PM,Sunday,0,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
21,220638624,11,SEND_ANY,2267,12,SEND_ANY,177805,None,America/Chicago,0,0,2017-12-31 19:21:11,2017-12-31,20171231,20180105,2017,12,31,07,21,11,PM,Sunday,0,0,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
22,220638625,11,SEND_ANY,1444,12,SEND_ANY,45560,None,America/Chicago,0,0,2017-12-22 15:18:00,2017-12-22,20171222,20171222,2017,12,22,03,18,00,PM,Friday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
23,220638626,11,SEND_ANY,2369,12,SEND_ANY,166599,None,America/Chicago,0,0,2017-12-15 16:55:17,2017-12-15,20171215,20171215,2017,12,15,04,55,17,PM,Friday,1,1,Q4\r,22,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1
24,220638627,11,SEND_ANY,2369,12,SEND_ANY,183778,None,America/Chicago,0,0,2017-12-15 16:35:02,2017-12-15,20171215,20171215,2017,12,15,04,35,02,PM,Friday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
25,220638628,11,SEND_ANY,2369,12,SEND_ANY,183129,None,America/Chicago,0,0,2017-12-15 16:37:11,2017-12-15,20171215,20171215,2017,12,15,04,37,11,PM,Friday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
26,220638956,4,VISIT,1859,3,VISIT,32941,33795.0,America/New_York,30,0,2017-12-28 15:00:00,2017-12-28,20171228,20171229,2017,12,28,03,00,00,PM,Thursday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
27,220638957,4,VISIT,1859,3,VISIT,45747,828531.0,America/New_York,30,0,2017-12-28 15:00:00,2017-12-28,20171228,20171229,2017,12,28,03,00,00,PM,Thursday,1,1,Q4\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
28,220638958,4,VISIT,1891,3,VISIT,18128,799476.0,America/New_York,30,0,2018-01-05 16:00:00,2018-01-05,20180105,20180105,2018,1,05,04,00,00,PM,Friday,1,1,Q1\r,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0
29,220638959,4,VISIT,1891,3,VISIT,25537,65200.0,America/New_York,30,0,2018-01-23 18:30:00,2018-01-23,20180123,20180126,2018,1,23,06,30,00,PM,Tuesday,1,1,Q1\r,25,3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,224290466,11,SEND_ANY,3339,12,SEND_ANY,311295,None,America/New_York,0,0,2018-01-26 13:45:00,2018-01-26,20180126,20180126,2018,1,26,01,45,00,PM,Friday,1,1,Q1\r,1186,14,0,1,0,1,1,0,1,1,1,0,0,1,1,1,1,1,1,1,1,0,1
999971,224290467,11,SEND_ANY,3339,12,SEND_ANY,86360,None,America/New_York,0,0,2018-01-26 14:00:00,2018-01-26,20180126,20180126,2018,1,26,02,00,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999972,224290468,11,SEND_ANY,3142,12,SEND_ANY,331701,None,America/Chicago,0,0,2018-01-26 14:00:00,2018-01-26,20180126,20180126,2018,1,26,02,00,00,PM,Friday,1,1,Q1\r,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1
999973,224290469,11,SEND_ANY,2985,12,SEND_ANY,196958,None,America/New_York,0,0,2018-01-26 15:01:00,2018-01-26,20180126,20180126,2018,1,26,03,01,00,PM,Friday,1,1,Q1\r,1088,13,0,1,0,1,1,0,1,1,0,0,0,1,1,1,1,1,1,1,1,0,1
999974,224290470,11,SEND_ANY,3691,12,SEND_ANY,236619,None,America/Chicago,0,0,2018-01-26 14:23:00,2018-01-26,20180126,20180126,2018,1,26,02,23,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999975,224290471,11,SEND_ANY,1324,12,SEND_ANY,63798,None,America/New_York,0,0,2018-01-26 15:37:00,2018-01-26,20180126,20180126,2018,1,26,03,37,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999976,224290472,11,SEND_ANY,1389,12,SEND_ANY,67975,None,America/New_York,0,0,2018-01-26 20:49:48,2018-01-26,20180126,20180126,2018,1,26,08,49,48,PM,Friday,1,0,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999977,224290473,11,SEND_ANY,1324,12,SEND_ANY,229493,None,America/New_York,0,0,2018-01-26 15:37:00,2018-01-26,20180126,20180126,2018,1,26,03,37,00,PM,Friday,1,1,Q1\r,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1
999978,224290474,11,SEND_ANY,3691,12,SEND_ANY,66228,None,America/Chicago,0,0,2018-01-26 14:46:00,2018-01-26,20180126,20180126,2018,1,26,02,46,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999979,224290475,11,SEND_ANY,3176,12,SEND_ANY,231337,None,America/New_York,0,0,2018-01-25 14:30:00,2018-01-25,20180125,20180126,2018,1,25,02,30,00,PM,Thursday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999980,224290476,11,SEND_ANY,3190,12,SEND_ANY,341784,None,America/New_York,0,0,2018-01-26 15:00:00,2018-01-26,20180126,20180126,2018,1,26,03,00,00,PM,Friday,1,1,Q1\r,32,3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1
999981,224290477,11,SEND_ANY,1911,12,SEND_ANY,51967,None,America/New_York,0,0,2018-01-26 18:38:01,2018-01-26,20180126,20180126,2018,1,26,06,38,01,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999982,224290478,11,SEND_ANY,3176,12,SEND_ANY,339554,None,America/New_York,0,0,2018-01-25 15:30:00,2018-01-25,20180125,20180126,2018,1,25,03,30,00,PM,Thursday,1,1,Q1\r,1004,12,0,1,0,1,1,0,1,1,0,0,0,0,1,1,1,1,1,1,1,0,1
999983,224290479,11,SEND_ANY,1911,12,SEND_ANY,61451,None,America/New_York,0,0,2018-01-26 14:08:30,2018-01-26,20180126,20180126,2018,1,26,02,08,30,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999984,224290480,11,SEND_ANY,1911,12,SEND_ANY,24263556,None,America/New_York,0,0,2018-01-26 15:27:00,2018-01-26,20180126,20180126,2018,1,26,03,27,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999985,224290481,11,SEND_ANY,3691,12,SEND_ANY,48633,None,America/Chicago,0,0,2018-01-26 15:05:00,2018-01-26,20180126,20180126,2018,1,26,03,05,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999986,224290482,11,SEND_ANY,1911,12,SEND_ANY,71924,None,America/New_York,0,0,2018-01-26 15:50:37,2018-01-26,20180126,20180126,2018,1,26,03,50,37,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999987,224290483,11,SEND_ANY,3747,12,SEND_ANY,26189,None,America/Chicago,0,0,2018-01-26 15:30:00,2018-01-26,20180126,20180126,2018,1,26,03,30,00,PM,Friday,1,1,Q1\r,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1
999988,224290484,11,SEND_ANY,1911,12,SEND_ANY,49277,None,America/New_York,0,0,2018-01-26 16:56:42,2018-01-26,20180126,20180126,2018,1,26,04,56,42,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999989,224290485,11,SEND_ANY,3176,12,SEND_ANY,236546,None,America/New_York,0,0,2018-01-25 16:30:00,2018-01-25,20180125,20180126,2018,1,25,04,30,00,PM,Thursday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999990,224290486,11,SEND_ANY,3285,12,SEND_ANY,338569,None,America/New_York,0,0,2018-01-26 15:02:57,2018-01-26,20180126,20180126,2018,1,26,03,02,57,PM,Friday,1,1,Q1\r,1304,15,0,1,0,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1
999991,224290487,11,SEND_ANY,1911,12,SEND_ANY,186056,None,America/New_York,0,0,2018-01-26 17:06:39,2018-01-26,20180126,20180126,2018,1,26,05,06,39,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999992,224290488,11,SEND_ANY,2065,12,SEND_ANY,39654728,385995781,America/New_York,0,0,2018-01-26 15:32:16,2018-01-26,20180126,20180126,2018,1,26,03,32,16,PM,Friday,1,1,Q1\r,463,6,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,1
999993,224290489,11,SEND_ANY,3277,12,SEND_ANY,18279,None,America/Chicago,0,0,2018-01-26 13:30:00,2018-01-26,20180126,20180126,2018,1,26,01,30,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999994,224290490,11,SEND_ANY,3176,12,SEND_ANY,344498,None,America/New_York,0,0,2018-01-25 16:00:00,2018-01-25,20180125,20180126,2018,1,25,04,00,00,PM,Thursday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999995,224290491,11,SEND_ANY,1333,12,SEND_ANY,232190,None,America/New_York,0,0,2018-01-25 20:30:00,2018-01-25,20180125,20180126,2018,1,25,08,30,00,PM,Thursday,1,0,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999996,224290492,11,SEND_ANY,1911,12,SEND_ANY,194897,None,America/New_York,0,0,2018-01-26 20:51:34,2018-01-26,20180126,20180126,2018,1,26,08,51,34,PM,Friday,1,0,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999997,224290493,11,SEND_ANY,3324,12,SEND_ANY,43379,None,America/New_York,0,0,2018-01-26 16:30:00,2018-01-26,20180126,20180126,2018,1,26,04,30,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1
999998,224290494,11,SEND_ANY,3176,12,SEND_ANY,335920,None,America/New_York,0,0,2018-01-25 19:00:00,2018-01-25,20180125,20180126,2018,1,25,07,00,00,PM,Thursday,1,0,Q1\r,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1
999999,224290495,11,SEND_ANY,3324,12,SEND_ANY,46239,None,America/New_York,0,0,2018-01-26 16:00:00,2018-01-26,20180126,20180126,2018,1,26,04,00,00,PM,Friday,1,1,Q1\r,87,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1